name: frontend

on: [push]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: npm install
        run: npm ci

      - run: npm run lint -- --no-fix

      - run: npm run build
